import time
print("Olá, seja bem-vindo aqui faremos o seu crachá de forma rápida e fácil!")
time.sleep(3)
nome = input("Digite o seu primeironome: ")
time.sleep(1)
idade = int(input("Digite a sua idade: "))
time.sleep(1)
cidade = input("Digite a sua cidade de nascimento: ")
time.sleep(1)
print("Gerando o seu crachá...")
time.sleep(2)
print("====================================")
print(f"           Nome: {nome}            ")
print("                                    ")
print("                                    ")
print("          ---------------           ")
print("          |             |           ")
print("          |             |           ")
print("          |             |           ")
print("          |    FOTO     |           ")
print("          |             |           ")
print("          |             |           ")
print("          |             |           ")
print("          ---------------           ")
print("                                    ")
print("                                    ")
print(f"         Idade: {idade}            ")
print(f"         Cidade: {cidade}          ")
print("                                    ")
print("====================================")
print("====================================")